output: bPk
multipole: 3
wedge: 0
skycut: 1
z: [0.5617]
with_redshift_bin: False
with_AP: True
z_AP: [0.5617]
Omega_m_AP: 0.307115
with_window: False
with_binning: True
with_fibercol: False

with_stoch: True
model: 2

with_bao: False

with_exact_time: True

xmin: [0.01]
xmax: [0.23]

covmat_file: [pybird/Covariance/CovChallengeA.dat]
spectrum_file: [pybird/DataSims/ps1D_Challenge_A.dat]

nd: 3.e-4
km: 0.7

with_bbn: True
omega_b_BBNcenter: 0.02214
omega_b_BBNsigma: 0.0005